# Generated by Django 5.1.7 on 2025-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
