# Generated by Django 5.1.7 on 2025-04-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
    ]
