# Generated by Django 5.1.7 on 2025-04-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
